# Generated by Django 2.2 on 2020-04-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_auto_20200420_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_handle',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_handle',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_handle',
            field=models.CharField(default='Empty', max_length=200),
        ),
    ]
