# Generated by Django 2.2 on 2020-04-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_auto_20200420_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'accepted'), ('D', 'declined'), ('C', 'cancelled'), ('P', 'pending')], default='P', max_length=2),
        ),
    ]
