# Generated by Django 2.2 on 2020-04-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_friendrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='friendshipRoom',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
