# Generated by Django 2.2 on 2020-04-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0007_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_status',
            field=models.CharField(blank=True, choices=[('ONN', 'online'), ('OFF', 'offline'), ('BUS', 'busy')], default='OFF', max_length=3),
        ),
    ]
