# Generated by Django 2.2 on 2020-04-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0008_profile_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_motto',
            field=models.CharField(blank=True, default='i am at work', max_length=200),
        ),
    ]
