# Generated by Django 2.2 on 2020-04-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0009_profile_personal_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_handle',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_handle',
            field=models.CharField(default='Empty', max_length=200),
        ),
    ]
