# Generated by Django 2.2 on 2020-04-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0011_auto_20200422_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='images/anon.png', max_length=200),
        ),
    ]
