# Generated by Django 2.2 on 2020-04-22 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_app', '0012_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_room', models.CharField(blank=True, max_length=200, null=True)),
                ('group_description', models.CharField(blank=True, max_length=500, null=True)),
                ('group_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
