# Generated by Django 2.2 on 2020-04-22 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0013_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group_rooms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_app.groups'),
        ),
    ]
