# Generated by Django 2.2 on 2020-04-23 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0015_auto_20200423_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_profile_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
