# Generated by Django 2.2 on 2020-04-23 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0016_auto_20200423_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupprofile',
            old_name='message',
            new_name='content',
        ),
    ]
